version: 0.2
env:
  variables:
      latest: "latest"
      name: "kalaikris"
phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - echo Build the docker image and pushed to docker hub
      - systemctl start docker
      - docker login -u kalaikris -p 9629540@kA
  build:
    commands:
      - docker pull nginx
      - docker tag react $name/nginx:$latest
  post_build:
    commands:
      - echo Push the image into docker hub
      - docker push $name/nginx:$latest
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages 
# used only for building and testing.
artifacts:
  files:
    - '**/*'
